Repository NBCampFinalProject/FromPet, pull requests merged in 2023-11, with the labels that each got.

#122 [Community] 커뮤니티 디테일 (삭제|수정) 추가했습니다.
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/intro/IntroActivity.kt
  app/src/main/res/drawable/cut.png
  app/src/main/res/drawable/delete.png
  app/src/main/res/drawable/done.png
  app/src/main/res/drawable/threedots.png
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/layout/item_my_message.xml
  app/src/main/res/menu/popup_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat

#123 [fix] 구글 로그인 재수정 및 스피너 적용
  app/src/main/java/com/example/frompet/data/model/CommunityHomeData.kt
  app/src/main/java/com/example/frompet/data/model/User.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepository.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
  app/src/main/java/com/example/frompet/ui/login/LoginActivity.kt
  app/src/main/java/com/example/frompet/ui/login/LoginViewModel.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/ui/login/googlelog/GoogleAcceptUpFragment.kt
  app/src/main/java/com/example/frompet/ui/login/googlelog/GoogleViewModel.kt
  app/src/main/res/layout/activity_member_info.xml
  app/src/main/res/layout/item_info_type.xml
Labels: ⚙Fix, 🎉Merge

#131 [커뮤니티홈프래그먼트] 데이터 구조 변경 및 패턴 적용
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/data/model/CommunityHomeData.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepository.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoAdapter.kt
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/values/strings.xml
Labels: ⚙Fix, 🎉Merge, 🛠Refector

#132 [FEAT]: HomeFragment필터기능 추가(성별,펫타입)거리는 아직안함
  app/src/main/java/com/example/frompet/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/data/model/Filter.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterViewModel.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
  app/src/main/res/layout/activity_home_filter.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat

#136 [community] 커뮤니티 태그 별 게시글 목록 뜨게 구현했습니다.
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailUpdateActivity.kt
  app/src/main/java/com/example/frompet/ui/map/NaverMapFragment.kt
  app/src/main/res/color/chip_background_exchange.xml
  app/src/main/res/color/chip_background_love.xml
  app/src/main/res/color/chip_background_share.xml
  app/src/main/res/color/chip_background_walk.xml
  app/src/main/res/drawable/heart_gray.png
  app/src/main/res/drawable/thumbsup.png
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_detail_update.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat, 🎨UI

#138 [Design] 모든 디테일 액티비티, [Faet] 로그아웃 시 토큰 널 값 설정
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatClickUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatListAdapter.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatLikeListFragment.kt
  app/src/main/java/com/example/frompet/ui/home/HomeDetailPage.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/ui/map/MapUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/res/drawable/icon_female.png
  app/src/main/res/drawable/icon_male.png
  app/src/main/res/drawable/icon_neuter.png
  app/src/main/res/drawable/icon_non_neuter.png
  app/src/main/res/layout/activity_chat_click_user_detail.xml
  app/src/main/res/layout/activity_chat_user_detail.xml
  app/src/main/res/layout/activity_home_detail_page.xml
  app/src/main/res/layout/activity_map_user_detail.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_chatlist.xml
  app/src/main/res/layout/sample.xml
  app/src/main/res/layout/sample2.xml
Labels: 🔨Feat, 🎨UI

#139 [커뮤니티 홈 프래그먼트] PetType에 따른 필터기능 적용
  app/src/main/java/com/example/frompet/SingleLiveEvent.kt
  app/src/main/java/com/example/frompet/data/model/CommunityHomeData.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepository.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryClick.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoAdapter.kt
Labels: ⚡Bug, ⚙Fix, 🎉Merge

#140 [home/chatfragment]필터기능 오류 수정,좋아요,싫어요버튼 눌렀을 때 스와이프되면서 똑같은기능
  app/src/main/java/com/example/frompet/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/data/model/Filter.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatFragment.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatLikeListFragment.kt
  app/src/main/java/com/example/frompet/ui/home/HomeEmptyFragment.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterViewModel.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/ui/setting/FriendsListAdapter.kt
  app/src/main/res/drawable/sampleiamge.jpg
  app/src/main/res/layout/activity_home_filter.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/fragment_chat_list.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_empty.xml
  app/src/main/res/layout/item_friends.xml
  app/src/main/res/raw/arrowright.json
  app/src/main/res/raw/swipeleft.json
  app/src/main/res/raw/swiperight.json
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ⚡Bug, 🔨Feat, 🎨UI

#142 [셋팅 프로필 액티비티] 디자인 수정
  app/src/main/java/com/example/frompet/ui/setting/SettingProfileActivity.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingViewModel.kt
  app/src/main/res/drawable/round_background.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/sample.xml
  app/src/main/res/layout/sample2.xml
Labels: 🎨UI

#143 [community] : 유저디테일 상당부분
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/values/colors.xml
Labels: 🔨Feat

#145 [map] 지도 화면 내 사용자 로드
  app/build.gradle
  app/src/main/java/com/example/frompet/MainActivity.kt
  app/src/main/java/com/example/frompet/data/repository/MapRepository.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/map/MapMakerBorder.kt
  app/src/main/java/com/example/frompet/ui/map/MapViewModel.kt
  app/src/main/java/com/example/frompet/ui/map/NaverMapFragment.kt
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat

#146 [커뮤니티 홈 프래그먼트, Imp, ViewModel 커뮤니티 액티비티 수정]
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/data/model/CommunityHomeData.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/commnunity/CategorySharedViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
Labels: ⚡Bug, ⚙Fix, 🎉Merge, 🛠Refector

#147 [community,homeFragment]커뮤니티홈프래그먼트카테고리분로,홈프래그먼트거리필터
  app/build.gradle
  app/src/main/java/com/example/frompet/MainActivity.kt
  app/src/main/java/com/example/frompet/data/model/CommunityHomeData.kt
  app/src/main/java/com/example/frompet/data/model/Filter.kt
  app/src/main/java/com/example/frompet/data/model/User.kt
  app/src/main/java/com/example/frompet/data/model/UserLocation.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterViewModel.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
  app/src/main/res/layout/activity_home_filter.xml
Labels: 🔨Feat, ⚙Fix

#149 [homefragment]내 위치기반으로 사용자 거리필터
  app/src/main/java/com/example/frompet/data/model/Filter.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterViewModel.kt
  app/src/main/res/layout/activity_chat_click_user_detail.xml
  app/src/main/res/layout/activity_chat_user_detail.xml
  app/src/main/res/layout/activity_home_filter.xml
  app/src/main/res/layout/activity_map_user_detail.xml
  app/src/main/res/layout/activity_profile.xml
Labels: 🔨Feat, ⚙Fix

#152 [커뮤니티 디테일,셋팅 프래그먼트] 댓글 기능, 로그아웃 바텀시트
  app/src/main/java/com/example/frompet/data/model/CommentData.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatClickUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatFragment.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommentAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/setting/FriendsListActivity.kt
  app/src/main/java/com/example/frompet/ui/setting/FriendsListAdapter.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/bottom_sheet_logout.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/item_friends.xml
  app/src/main/res/layout/item_re_reply.xml
  app/src/main/res/layout/item_reply.xml
  app/src/main/res/layout/sample.xml
  app/src/main/res/layout/sample2.xml
Labels: 🔨Feat, 🎨UI

#153 [커뮤니티 디테일, 셋팅 프로필] 댓글 정보 뜨게 변경, 펫 성별,종류 아이콘 위치 변경
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommentAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingProfileActivity.kt
Labels: 🔨Feat, 🎨UI

#154 [커뮤니티 카테고리 프래그먼트, 액티비티 검색어 필터 수정]
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
  app/src/main/res/drawable/border_search_bar.xml
  app/src/main/res/drawable/ic_search_frag_img.xml
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/fragment_communityhome.xml
Labels: 🔨Feat, 🎨UI, ⚙Fix, 🎉Merge

#155 [community.fragment]삭제, 추가,칩버튼 변경
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterActivity.kt
  app/src/main/java/com/example/frompet/util/FormatDate.kt
  app/src/main/java/com/example/frompet/util/GetAddressGeocoder.kt
  app/src/main/java/com/example/frompet/util/ViewCountManager.kt
  app/src/main/res/layout/item_community.xml
  app/src/main/res/values/colors.xml
Labels: 🔨Feat, 🎨UI, ⚙Fix

#156 [커뮤니티 디테일] 댓글 프로필 , 댓글 삭제 기능
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/data/model/CommentData.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommentAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommentModify.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/res/layout/activity_comment_modify.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/bottom_sheet_layout.xml
  app/src/main/res/layout/item_reply.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat, ⚙Fix

#159 [MAP] 맵 화면 이동 시 데이터 삭제 및 로드
  app/build.gradle
  app/src/main/java/com/example/frompet/data/model/UserLocation.kt
  app/src/main/java/com/example/frompet/data/repository/MapRepository.kt
  app/src/main/java/com/example/frompet/data/repository/map/MapRepository.kt
  app/src/main/java/com/example/frompet/data/repository/map/MapRepositoryImpl.kt
  app/src/main/java/com/example/frompet/ui/map/MapViewModel.kt
  app/src/main/java/com/example/frompet/ui/map/NaverMapFragment.kt
Labels: 🔨Feat

#160 [UI] 맵 drawable 추가하였습니다.
  app/src/main/res/drawable/circle.png
  app/src/main/res/drawable/reset.png
Labels: 🎨UI

#161 [커뮤니티 디테일 액티비티] 댓글 수정기능, 댓글 좋아요 기능, 작성자에 따라서 바텀시트 다르게,신고기능,댓글 추가시 키보드 내려가게
  app/src/main/java/com/example/frompet/data/model/CommentData.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommentAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommentModify.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/map/NaverMapFragment.kt
  app/src/main/res/drawable/icon_sel_thumb.xml
  app/src/main/res/drawable/icon_unsel_thumb.xml
  app/src/main/res/layout/activity_comment_modify.xml
  app/src/main/res/layout/bottom_sheet_layout2.xml
  app/src/main/res/layout/item_reply.xml
Labels: 🔨Feat, 🎨UI, ⚙Fix

#162 [community]커뮤프래그먼트검색바수정등등
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommentAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFilterActivity.kt
  app/src/main/res/drawable/icon_up.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_communityhome.xml
Labels: 🔨Feat, 🎨UI, ⚙Fix

#168 [community]게시물작성할 때 사진추가 기능구현입니다.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pet/frompet/data/model/CommunityData.kt
  app/src/main/java/com/pet/frompet/ui/chat/activity/ChatUserDetailActivity.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/communitydetail/CommunityDetailUpdateActivity.kt
  app/src/main/java/com/pet/frompet/ui/map/MapUserDetailActivity.kt
  app/src/main/res/drawable/ib_button_radius.xml
  app/src/main/res/drawable/image_radius.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_detail_update.xml
  app/src/main/res/layout/activity_map_user_detail.xml
  app/src/main/res/layout/item_community.xml
Labels: 🔨Feat

#170 [map] viewmodel로 리펙토링했습니다
  app/src/main/java/com/pet/frompet/ui/map/MapViewModel.kt
  app/src/main/java/com/pet/frompet/ui/map/NaverMapFragment.kt
Labels: 🔨Feat

#172 [community.fragment]커뮤니티 액티비티디테일 게시글 본인만 삭제하게
  app/src/main/java/com/pet/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🔨Feat

#173 [커뮤니티 디테일 페이지] 대댓글 기능
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pet/frompet/data/model/CommentData.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/communitydetail/CommentAdapter.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/communitydetail/ReCommentActivity.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/communitydetail/ReCommentModify.kt
  app/src/main/res/layout/activity_re_comment_modify.xml
Labels: 🔨Feat

#174 [셋팅 프래그먼트 설정탭 추가] MoreActivity추가, 회원 탈퇴 및 로그아웃 옮김
  app/keyStore/keyStore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pet/frompet/data/repository/firebase/BaseAuthenticator.kt
  app/src/main/java/com/pet/frompet/data/repository/firebase/FirebaseAuthenticator.kt
  app/src/main/java/com/pet/frompet/data/repository/user/AuthRepository.kt
  app/src/main/java/com/pet/frompet/data/repository/user/BaseAuthRepository.kt
  app/src/main/java/com/pet/frompet/data/repository/user/UserRepositoryImp.kt
  app/src/main/java/com/pet/frompet/ui/intro/IntroActivity.kt
  app/src/main/java/com/pet/frompet/ui/login/LoginViewModel.kt
  app/src/main/java/com/pet/frompet/ui/more/MoreActivity.kt
  app/src/main/java/com/pet/frompet/ui/more/MorePasswordResetActivity.kt
  app/src/main/java/com/pet/frompet/ui/more/MorePasswordResetViewModel.kt
  app/src/main/java/com/pet/frompet/ui/more/signout/SignOutActivity.kt
  app/src/main/java/com/pet/frompet/ui/setting/SettingFragment.kt
  app/src/main/res/drawable/arrow_right.xml
  app/src/main/res/layout/activity_more.xml
  app/src/main/res/layout/activity_more_password_reset.xml
  app/src/main/res/layout/activity_sign_out.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: 🔨Feat, ⚙Fix, 🎉Merge

#177 [bottom_nav_menu] 아이콘 변경
  app/src/main/java/com/pet/frompet/data/model/CommentData.kt
  app/src/main/java/com/pet/frompet/data/model/ReCommentData.kt
  app/src/main/java/com/pet/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/pet/frompet/ui/map/NaverMapFragment.kt
  app/src/main/res/drawable/icon_chat.xml
  app/src/main/res/drawable/icon_commu.xml
  app/src/main/res/drawable/icon_home.xml
  app/src/main/res/drawable/icon_map.xml
  app/src/main/res/drawable/icon_sel_chat.xml
  app/src/main/res/drawable/icon_sel_commu.xml
  app/src/main/res/drawable/icon_sel_home.xml
  app/src/main/res/drawable/icon_sel_map.xml
  app/src/main/res/drawable/icon_sel_setting.xml
  app/src/main/res/drawable/icon_setting.xml
  app/src/main/res/drawable/icon_unsel_chat.xml
  app/src/main/res/drawable/icon_unsel_commu.xml
  app/src/main/res/drawable/icon_unsel_home.xml
  app/src/main/res/drawable/icon_unsel_map.xml
  app/src/main/res/drawable/icon_unsel_setting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bottom_nav_menu.xml
Labels: 🎨UI

#178 [MoreActivity 수정안] 회원탈퇴시 뒤로가기 버튼을 누르면 뒤에 있던 액티비티가 실행되는 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pet/frompet/ui/login/LoginActivity.kt
  app/src/main/java/com/pet/frompet/ui/login/PasswordResetActivity.kt
  app/src/main/java/com/pet/frompet/ui/more/MoreActivity.kt
  app/src/main/java/com/pet/frompet/ui/more/signout/LoadingActivity.kt
  app/src/main/java/com/pet/frompet/ui/more/signout/SignOutActivity.kt
  app/src/main/res/layout/activity_loading.xml
  app/src/main/res/layout/activity_login.xml
Labels: ⚙Fix, 🎉Merge

#180 [main액티비티] 위치권한 허용알림 후 재실행 메시지
  app/src/main/java/com/pet/frompet/MainActivity.kt
  app/src/main/java/com/pet/frompet/ui/home/HomeFilterViewModel.kt
Labels: ⚡Bug
