Repository NBCampFinalProject/FromPet, pull requests merged in 2023-10, with the labels that each got.

#6 [Main] 아이콘 색 보이게 수정
  app/src/main/java/com/example/frompet/MainActivity.kt
  app/src/main/res/drawable/chat.png
  app/src/main/res/drawable/commu.png
  app/src/main/res/drawable/home.png
  app/src/main/res/drawable/icon_chat_unselected.xml
  app/src/main/res/drawable/icon_commu_unselected.xml
  app/src/main/res/drawable/icon_home_unselected.xml
  app/src/main/res/drawable/icon_map_unselected.xml
  app/src/main/res/drawable/icon_setting_unselected.xml
  app/src/main/res/drawable/map.png
  app/src/main/res/drawable/selector_icon_home.xml
  app/src/main/res/drawable/setting.png
  app/src/main/res/menu/bottom_nav_menu.xml
Labels: ⚙Fix

#8 [ChatFrag]홈에서 매칭 후 간단한 채팅기능
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/chating/ChatFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatListFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatingFragment.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatHomeAdapter.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatListAdapter.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/chating/adapter/ViewPagerAdapter.kt
  app/src/main/java/com/example/frompet/commutiy/CommunicationFragment.kt
  app/src/main/java/com/example/frompet/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/ChatViewModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
  app/src/main/java/com/example/frompet/map/MapFragment.kt
  app/src/main/java/com/example/frompet/setting/SettingFragment.kt
  app/src/main/res/drawable/back_btn.xml
  app/src/main/res/drawable/favorite_border.xml
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/heartbtn.xml
  app/src/main/res/drawable/iv_camera.xml
  app/src/main/res/drawable/iv_send.png
  app/src/main/res/drawable/leftbubble.9.png
  app/src/main/res/drawable/rightbubble.9.png
  app/src/main/res/layout/activity_chat_message.xml
  app/src/main/res/layout/activity_chat_user_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/fragment_chat_list.xml
  app/src/main/res/layout/fragment_chating.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_chat_message.xml
  app/src/main/res/layout/item_chathome.xml
  app/src/main/res/layout/item_chatlist.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/raw/dislike.json
  app/src/main/res/raw/like.json
  app/src/main/res/values/colors.xml
Labels: 🔨Feat, 🎨UI, 🎉Merge

#11 [Map] MapFragment 지도 화면에 띄우기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/map/MapFragment.kt
  app/src/main/res/layout/fragment_map.xml
  settings.gradle
Labels: 🔨Feat

#12 [setting] 설정 프래그먼트 디자인
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/java/com/example/frompet/main/MainActivity.kt
  app/src/main/java/com/example/frompet/setting/ProfileActivity.kt
  app/src/main/java/com/example/frompet/setting/SettingFragment.kt
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/drawable/icon_back.xml
  app/src/main/res/drawable/icon_camera.xml
  app/src/main/res/drawable/kakaotalk_20230825_222509794_01.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/themes.xml
Labels: 🎨UI

#14 [DESIGN] 설정 프래그먼트 스크롤 뷰 추가
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: 🔨Feat, 🎨UI

#15 [login] 이미지 저장 완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/login/LoginActivity.kt
  app/src/main/java/com/example/frompet/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
  app/src/main/java/com/example/frompet/map/MapFragment.kt
  app/src/main/res/drawable/leftbubble.9.png
  app/src/main/res/layout/activity_member_info.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_home_card.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  gradle.properties
  settings.gradle
Labels: ⚡Bug, 🔨Feat, 🎉Merge

#16 [Chat]채팅신청한 사람 지워지게 매칭됐을 시
  app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatListFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatListAdapter.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
  app/src/main/res/drawable/back_btn.xml
  app/src/main/res/drawable/cat.png
  app/src/main/res/drawable/chick.png
  app/src/main/res/drawable/fish.png
  app/src/main/res/drawable/fox.png
  app/src/main/res/drawable/frog.png
  app/src/main/res/drawable/hate.png
  app/src/main/res/drawable/loginprofile.png
  app/src/main/res/drawable/loginprofile2.png
  app/src/main/res/drawable/pig.png
  app/src/main/res/drawable/raccoon.png
  app/src/main/res/drawable/snake.png
  app/src/main/res/drawable/splash.png
  app/src/main/res/layout/activity_chat_user_detail.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/fragment_chat_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ⚡Bug, 🔨Feat, 🎨UI

#19 [Chat}채팅프래그먼트 이미지불러온거 적용입니다
  app/build.gradle
  app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatHomeAdapter.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatListAdapter.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/ChatViewModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/item_chat_message.xml
  app/src/main/res/layout/item_chathome.xml
  app/src/main/res/menu/bottom_nav_menu.xml
Labels: 🔨Feat, ⚙Fix

#21 [FEAT] 설정프래그먼트에 데이터 불러오기
  app/build.gradle
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
  app/src/main/java/com/example/frompet/setting/ProfileActivity.kt
  app/src/main/java/com/example/frompet/setting/SettingFragment.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: 🔨Feat, 🎨UI

#22 [FEAT] 설정 프레그먼트 정보 변경
  app/src/main/java/com/example/frompet/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/SettingViewModel.kt
  app/src/main/java/com/example/frompet/setting/ProfileActivity.kt
  app/src/main/java/com/example/frompet/setting/SettingFragment.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: 🔨Feat

#23 [ChatFrag]챗프래그먼트 최신메시지순 정렬
  app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatListFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatViewModel.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatHomeAdapter.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/login/viewmodel/ChatViewModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
  app/src/main/res/drawable/circle_background.xml
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/item_chathome.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ⚡Bug, 🔨Feat, ⚙Fix

#25 [Merge] 홈프래그먼트 카드뷰
  app/build.gradle
  app/src/main/java/com/example/frompet/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/home/adapter/HomeAdapter.kt
  app/src/main/java/com/example/frompet/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/res/drawable/gradient_shape.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/item_home_card.xml
  settings.gradle
Labels: 🔨Feat, 🎉Merge

#26 [FIX] 사진 변경시 튕기는 버그 수정
  app/src/main/java/com/example/frompet/setting/ProfileActivity.kt
Labels: ⚙Fix

#27 [Fix] :nullability고려해서 간단한 수정 홈프래그먼트 ,homefrag 하트 수정
  app/src/main/java/com/example/frompet/chating/ChatFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatListFragment.kt
  app/src/main/java/com/example/frompet/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
  app/src/main/java/com/example/frompet/map/MapFragment.kt
  app/src/main/res/layout/fragment_chat_home.xml
Labels: ⚡Bug, ⚙Fix

#30 [Map] 사용자 현재 위치 가져오기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/main/MainActivity.kt
  app/src/main/java/com/example/frompet/map/MapFragment.kt
  app/src/main/java/com/example/frompet/map/NaverMapFragment.kt
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat

#31 [Chat]채팅하면서 폰에있는 사진보내기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatPullScreenActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatViewModel.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchViewModel.kt
  app/src/main/java/com/example/frompet/setting/SettingFragment.kt
  app/src/main/res/drawable/chat.9/res/drawable-hdpi/chat.9.png
  app/src/main/res/drawable/chat.9/res/drawable-mdpi/chat.9.png
  app/src/main/res/drawable/chat.9/res/drawable-xhdpi/chat.9.png
  app/src/main/res/drawable/chat.9/res/drawable-xxhdpi/chat.9.png
  app/src/main/res/drawable/chat.9/res/drawable-xxxhdpi/chat.9.png
  app/src/main/res/layout/activity_chat_message.xml
  app/src/main/res/layout/activity_chat_pull_screen.xml
  app/src/main/res/layout/item_chat_message.xml
  app/src/main/res/layout/item_chathome.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat, ⚙Fix

#34 [Chat]메시지어댑터뷰타입나누고,수정할부분 수정했습니다
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/chating/ChatClickUserDetailActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatListFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatHomeAdapter.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/login/viewmodel/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/setting/SettingFragment.kt
  app/src/main/java/com/example/frompet/util/ToastUtil.kt
  app/src/main/res/drawable/chat1.9.png
  app/src/main/res/drawable/chat2.9.png
  app/src/main/res/layout/activity_chat_click_user_detail.xml
  app/src/main/res/layout/activity_chat_pull_screen.xml
  app/src/main/res/layout/item_chat_message.xml
  app/src/main/res/layout/item_my_message.xml
  app/src/main/res/layout/item_other_message.xml
  app/src/main/res/values/colors.xml
Labels: ⚡Bug, ⚙Fix

#35 [chat UI, Home] 채팅, 홈 수정
  app/build.gradle
  app/src/main/java/com/example/frompet/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/home/adapter/HomeAdapter.kt
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/fragment_chat_list.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/xml/fragment_chat_home_scene.xml
  app/src/main/res/xml/fragment_chat_list_scene.xml
Labels: 🎨UI, ⚙Fix

#38 [FIX]: 메시지어댑터 with로 적용
  app/src/main/java/com/example/frompet/chating/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatViewModel.kt
  app/src/main/java/com/example/frompet/chating/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/login/data/UserModel.kt
  app/src/main/res/layout/activity_chat_message.xml
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/fragment_chat_list.xml
Labels: ⚙Fix

#40 [FEAT] 채팅 목록 최신으로 올라오게 하기
  app/src/main/java/com/example/frompet/chating/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/chating/ChatPullScreenActivity.kt
  app/src/main/java/com/example/frompet/setting/ProfileActivity.kt
  app/src/main/java/com/example/frompet/setting/SettingFragment.kt
  app/src/main/res/drawable/iv_send.png
  app/src/main/res/drawable/iv_send.xml
  app/src/main/res/layout/activity_chat_message.xml
  app/src/main/res/layout/activity_chat_pull_screen.xml
  app/src/main/res/layout/sample_user_detail.xml
Labels: 🔨Feat, 🎨UI

#44 [Home]홈프래그먼트에서 중복카드 안보이게
  app/src/main/java/com/example/frompet/ui/chat/ChatFragment.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatLikeListFragment.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatPullScreenActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatViewModel.kt
  app/src/main/java/com/example/frompet/ui/chat/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ViewPagerAdapter.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
  app/src/main/res/layout/activity_chat_click_user_detail.xml
  app/src/main/res/layout/activity_chat_message.xml
  app/src/main/res/layout/activity_chat_user_detail.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/fragment_chat_list.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_chatlist.xml
  app/src/main/res/layout/item_my_message.xml
  app/src/main/res/layout/item_other_message.xml
  app/src/main/res/layout/sample_user_detail.xml
  app/src/main/res/values/colors.xml
Labels: 🔨Feat, ⚙Fix

#46 [FIX] Dagger 2 Hilt 로그인 및 회원 가입 적용
  app/build.gradle
  app/src/main/java/com/example/frompet/data/repository/AuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/UserRepository.kt
  app/src/main/java/com/example/frompet/data/repository/UserRepositoryImp.kt
  app/src/main/java/com/example/frompet/di/AppModule.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/ui/login/LoginActivity.kt
  app/src/main/java/com/example/frompet/ui/login/LoginupViewModel.kt
  app/src/main/java/com/example/frompet/ui/login/SingUpActivity.kt
  app/src/main/java/com/example/frompet/ui/login/UserViewModel.kt
  app/src/main/res/drawable/ic_error.xml
  app/src/main/res/drawable/ic_mail.xml
  app/src/main/res/drawable/ic_password.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sing_up.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: 🔨Feat, 🎨UI, ⚙Fix, 🛠Refector

#47 [Chat]:채팅프래그먼트 전체적인 리팩토링
  app/src/main/java/com/example/frompet/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/data/repository/chat/ChatRepository.kt
  app/src/main/java/com/example/frompet/data/repository/chat/ChatRepositoryImpl.kt
  app/src/main/java/com/example/frompet/data/repository/message/MessageRepository.kt
  app/src/main/java/com/example/frompet/data/repository/message/MessageRepositoryImpl.kt
  app/src/main/java/com/example/frompet/data/repository/user/AuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/user/BaseAuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/user/UserRepositoryImp.kt
  app/src/main/java/com/example/frompet/di/AppModule.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatLikeListFragment.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatViewModel.kt
  app/src/main/java/com/example/frompet/ui/chat/MessageViewModel.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatHomeAdapter.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/ui/login/UserViewModel.kt
  app/src/main/res/layout/activity_chat_message.xml
  app/src/main/res/values/strings.xml
Labels: ⚡Bug, 🛠Refector

#57 [map] 사용자 프로필사진으로 마커 이미지 변경
  app/build.gradle
  app/src/main/java/com/example/frompet/ui/map/NaverMapFragment.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_map.xml
Labels: 🔨Feat

#59 [FEAT] fcm 토큰 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/MainActivity.kt
  app/src/main/java/com/example/frompet/data/repository/firebase/MyFirebaseMessagingService.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatPullScreenActivity.kt
  app/src/main/java/com/example/frompet/ui/setting/FCMTokenManagerViewModel.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/res/layout/activity_chat_pull_screen.xml
Labels: 🔨Feat

#60 [Fix] : 로그인 기능 강화중
  app/src/main/java/com/example/frompet/data/repository/user/AuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/user/BaseAuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/user/UserRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/login/LoginupViewModel.kt
  app/src/main/res/layout/activity_member_info.xml
Labels: ⚙Fix, 🎉Merge, 🛠Refector

#64 [Chat]:채팅방 목록에 마지막메시지시간
  app/build.gradle
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatHomeAdapter.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatMessageAdapter.kt
  app/src/main/res/layout/item_chathome.xml
Labels: 🔨Feat

#65 [Chat] 채팅방뷰타입 세개로 날짜별로정렬
  app/src/main/java/com/example/frompet/data/model/ChatMessage.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatMessageAdapter.kt
  app/src/main/res/layout/item_chathome.xml
  app/src/main/res/layout/item_date_header.xml
  app/src/main/res/values/colors.xml
Labels: 🔨Feat, ⚙Fix

#68 [Community] UI 만들었습니다
  app/src/main/java/com/example/frompet/ui/commnunity/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/item_coummunication.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat, 🎨UI

#69 [USERDETAIL] 전체적인 디자인수정
  app/src/main/java/com/example/frompet/data/repository/message/MessageRepository.kt
  app/src/main/java/com/example/frompet/data/repository/message/MessageRepositoryImpl.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/viewmodel/MessageViewModel.kt
  app/src/main/res/drawable/age.png
  app/src/main/res/drawable/animalprofile.png
  app/src/main/res/drawable/des.png
  app/src/main/res/drawable/dislike.xml
  app/src/main/res/drawable/gender.png
  app/src/main/res/drawable/gradient_shape.xml
  app/src/main/res/drawable/intro.png
  app/src/main/res/drawable/like.xml
  app/src/main/res/drawable/name.png
  app/src/main/res/drawable/ribbon.png
  app/src/main/res/drawable/rounded_corner.xml
  app/src/main/res/drawable/type.png
  app/src/main/res/layout/activity_chat_click_user_detail.xml
  app/src/main/res/layout/activity_chat_user_detail.xml
  app/src/main/res/layout/fragment_home_bottom_sheet_dialog.xml
  app/src/main/res/layout/item_chatlist.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/layout/sample2_user_detail.xml
Labels: ⚡Bug, 🎨UI

#71 [FEAT] 친구창 만드는 중
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/ui/setting/FriendsListActivity.kt
  app/src/main/java/com/example/frompet/ui/setting/FriendsListAdapter.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingProfileActivity.kt
  app/src/main/res/drawable/icon_camera.xml
  app/src/main/res/drawable/icon_search.xml
  app/src/main/res/layout/activity_friends_list.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/sample_user_detail.xml
  app/src/main/res/raw/loading.gif
Labels: 🔨Feat, 🎨UI

#72 [community] drawable 추가하였습니다.
  app/src/main/res/drawable/dog.png
  app/src/main/res/drawable/pen.png
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_communityhome.xml
Labels: 🎨UI

#73 [Fix] 회원 정보 UI 및 로직 변경
  app/build.gradle
  app/src/main/java/com/example/frompet/MainActivity.kt
  app/src/main/java/com/example/frompet/di/AppModule.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatClickUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeBottomSheetFragment.kt
  app/src/main/java/com/example/frompet/ui/login/LoginActivity.kt
  app/src/main/java/com/example/frompet/ui/login/LoginViewModel.kt
  app/src/main/java/com/example/frompet/ui/login/LoginupViewModel.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/ui/login/PasswordResetActivity.kt
  app/src/main/java/com/example/frompet/ui/login/SingUpActivity.kt
  app/src/main/java/com/example/frompet/ui/login/UserViewModel.kt
  app/src/main/res/drawable/calendar_month_24px.xml
  app/src/main/res/drawable/custom_progressbar.xml
  app/src/main/res/drawable/im_login.jpg
  app/src/main/res/drawable/pets_24px.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_member_info.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ⚙Fix, 🎉Merge, 🛠Refector

#78 [FEAT] 친구목록 보이고 누를 때 디테일 페이지로 이동
  app/src/main/java/com/example/frompet/ui/setting/FriendsListActivity.kt
  app/src/main/java/com/example/frompet/ui/setting/FriendsListAdapter.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingProfileActivity.kt
  app/src/main/res/layout/activity_friends_list.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_coummunication.xml
  app/src/main/res/layout/item_friends.xml
Labels: 🔨Feat

#79 [Community] 데이터 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/data/model/CommunityHomeData.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitAdd/CommunityAddActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat

#80 [DESIGN] 설정 프래그먼트 아이콘 변경
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/res/drawable/icon_alarm_off.xml
  app/src/main/res/drawable/icon_alarm_on.xml
  app/src/main/res/drawable/icon_friends.xml
  app/src/main/res/drawable/icon_modify.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_setting.xml
Labels: 🎨UI

#81 [REFATOR] :간단한 코드정리 &xml정리
  app/src/main/java/com/example/frompet/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/data/model/ChatMessage.kt
  app/src/main/java/com/example/frompet/data/repository/message/MessageRepository.kt
  app/src/main/java/com/example/frompet/data/repository/message/MessageRepositoryImpl.kt
  app/src/main/java/com/example/frompet/ui/chat/ChatItemConverter.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatMessageActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/activity/ChatUserDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/chat/dialog/ChatExitDialog.kt
  app/src/main/java/com/example/frompet/ui/chat/viewmodel/MessageViewModel.kt
  app/src/main/res/layout/item_chathome.xml
  app/src/main/res/values/colors.xml
Labels: ⚙Fix, 🛠Refector

#82 [GoogleLog] 구글로그인 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/data/model/SignInResult.kt
  app/src/main/java/com/example/frompet/data/model/SignState.kt
  app/src/main/java/com/example/frompet/data/repository/firebase/BaseAuthenticator.kt
  app/src/main/java/com/example/frompet/data/repository/firebase/FirebaseAuthenticator.kt
  app/src/main/java/com/example/frompet/data/repository/user/AuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/user/BaseAuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/user/UserRepositoryImp.kt
  app/src/main/java/com/example/frompet/di/AppModule.kt
  app/src/main/java/com/example/frompet/ui/login/LoginActivity.kt
  app/src/main/java/com/example/frompet/ui/login/LoginViewModel.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🔨Feat, 🎉Merge

#84 [FIX] 커뮤니티 연결, UI 수정하였습니다.
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/layout/item_coummunication.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI, ⚙Fix

#86 [CONFLICT] 커뮤니티 오류 수정 중입니다.
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/res/drawable/pen.png
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/layout/item_coummunication.xml
Labels: 🔨Feat

#87 [Community]match많은 순으로 슬라이드 표시
  app/src/main/java/com/example/frompet/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/ImageSliderAdapter.kt
  app/src/main/res/drawable/badge1.png
  app/src/main/res/drawable/badge2.png
  app/src/main/res/drawable/badge3.png
  app/src/main/res/drawable/badge4.png
  app/src/main/res/drawable/badge5.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_member_info.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/item_slider_image.xml
  app/src/main/res/values/colors.xml
Labels: 🔨Feat

#89 [커뮤니티] 커뮤니티 연결 수정 중입니다.
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
Labels: ⚙Fix

#90 [Comu]간단한 디자인&공지사항 매칭자 숫자표현
  app/src/main/java/com/example/frompet/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CommunityHomeFragment.kt
  app/src/main/res/anim/slide_down.xml
  app/src/main/res/anim/slide_up.xml
  app/src/main/res/drawable/frame.png
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/item_slider_image.xml
  app/src/main/res/values/strings.xml
Labels: 🔨Feat, 🎨UI

#93 [Fix] 구글 로그인 / 인트로 적용
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/data/model/PageItem.kt
  app/src/main/java/com/example/frompet/ui/intro/IntroActivity.kt
  app/src/main/java/com/example/frompet/ui/intro/IntroAdapter.kt
  app/src/main/java/com/example/frompet/ui/intro/PagerViewHolder.kt
  app/src/main/java/com/example/frompet/ui/login/GoogleAcceptUpFragment.kt
  app/src/main/java/com/example/frompet/ui/login/GoogleViewModel.kt
  app/src/main/java/com/example/frompet/ui/login/LoginActivity.kt
  app/src/main/java/com/example/frompet/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/ic_left_arrow.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_member_info.xml
  app/src/main/res/layout/fragment_google_accept_up.xml
  app/src/main/res/layout/layout_intro_pager_item.xml
Labels: 🎨UI, ⚙Fix, 🛠Refector

#95 [DESIGN] :앱아이콘
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: 🎨UI

#97 [community] 커뮤니티 UI 추가했습니다
  app/src/main/java/com/example/frompet/ui/commnunity/AddExitDialog.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/res/drawable/border_comment.xml
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/community_add_bottom_sheet_exit.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI

#100 [Home]홈프래그먼트 카드 다썻을때 처리
  app/src/main/java/com/example/frompet/MatchSharedViewModel.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communitydetail/CommunityDetailActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeEmptyFragment.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_empty.xml
  app/src/main/res/raw/search.json
  app/src/main/res/values/strings.xml
Labels: 🔨Feat

#101 [fix] google 간편 로그인
  app/build.gradle
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepository.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
  app/src/main/java/com/example/frompet/data/repository/firebase/BaseAuthenticator.kt
  app/src/main/java/com/example/frompet/data/repository/firebase/FirebaseAuthenticator.kt
  app/src/main/java/com/example/frompet/data/repository/user/AuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/user/BaseAuthRepository.kt
  app/src/main/java/com/example/frompet/data/repository/user/UserRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryViewModel.kt
  app/src/main/java/com/example/frompet/ui/login/LoginActivity.kt
  app/src/main/java/com/example/frompet/ui/login/googlelog/GoogleAcceptUpFragment.kt
  app/src/main/java/com/example/frompet/ui/login/googlelog/GoogleViewModel.kt
  app/src/main/res/layout/fragment_communityhome.xml
Labels: ⚡Bug, 🔨Feat, 🎉Merge

#103 [DESIGN] 프로필 수정 페이지 ui 변경
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatMessageAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingProfileActivity.kt
  app/src/main/res/drawable/border_comment.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: 🎨UI

#105 [COMU] Comu매칭 뱃지 교환 frame 변경
  app/src/main/res/drawable/badge1.png
  app/src/main/res/drawable/badge2.png
  app/src/main/res/drawable/badge3.png
  app/src/main/res/drawable/badge4.png
  app/src/main/res/drawable/badge5.png
  app/src/main/res/drawable/gallery.png
  app/src/main/res/drawable/icon_1_badge.xml
  app/src/main/res/drawable/icon_2_badge.xml
  app/src/main/res/drawable/icon_3_badge.xml
  app/src/main/res/drawable/icon_4_badge.xml
  app/src/main/res/drawable/icon_5_badge.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/item_slider_image.xml
Labels: 🎨UI

#106 [FIX] 구글 로그인 오류 수정
  app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/ui/login/googlelog/GoogleAcceptUpFragment.kt
Labels: ⚙Fix, 🎉Merge

#110 [Community] viewmodel 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/data/model/CommunityData.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityAdapter.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityViewModel.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityadd/CommunityAddActivity.kt
Labels: 🛠Refector

#113 [feat] 회원정보 반려동물 종류 커스텀 스피넷
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepository.kt
  app/src/main/java/com/example/frompet/data/repository/category/CategoryRepositoryImp.kt
  app/src/main/java/com/example/frompet/ui/commnunity/communityhome/CategoryViewModel.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoActivity.kt
  app/src/main/java/com/example/frompet/ui/login/MemberInfoAdapter.kt
  app/src/main/res/layout/activity_member_info.xml
  app/src/main/res/layout/item_info_type.xml
Labels: 🔨Feat

#115 [DESIGN] 전체적인 ui 수정 중
  app/src/main/res/drawable/icon_google.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sing_up.xml
  app/src/main/res/layout/fragment_chat_home.xml
  app/src/main/res/layout/fragment_chat_list.xml
Labels: 🎨UI

#117 [FCM]알람스위치버튼이랑 알람 연동
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/frompet/MainActivity.kt
  app/src/main/java/com/example/frompet/data/repository/chat/ChatRepositoryImpl.kt
  app/src/main/java/com/example/frompet/data/repository/fcm/FCMNotificationRepository.kt
  app/src/main/java/com/example/frompet/data/repository/fcm/FCMNotificationRepositoryImpl.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatListAdapter.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatLikeListFragment.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
  app/src/main/java/com/example/frompet/ui/setting/SettingFragment.kt
  app/src/main/java/com/example/frompet/ui/setting/fcm/FCMTokenManager.kt
  app/src/main/res/layout/activity_chat_click_user_detail.xml
  app/src/main/res/layout/activity_chat_message.xml
  app/src/main/res/layout/activity_chat_user_detail.xml
  app/src/main/res/layout/activity_community.xml
  app/src/main/res/layout/activity_community_add.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/fragment_communityhome.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_chatlist.xml
  app/src/main/res/raw/swipeleft.json
  app/src/main/res/raw/swiperight.json
  app/src/main/res/values/colors.xml
Labels: 🔨Feat, 🎨UI, ⚙Fix

#118 [FIX]다양한오류.간단한디자인
  app/src/main/java/com/example/frompet/data/repository/chat/ChatRepositoryImpl.kt
  app/src/main/java/com/example/frompet/ui/chat/adapter/ChatHomeAdapter.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatHomeFragment.kt
  app/src/main/java/com/example/frompet/ui/chat/fragment/ChatLikeListFragment.kt
  app/src/main/java/com/example/frompet/ui/commnunity/community/CommunityActivity.kt
  app/src/main/java/com/example/frompet/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/styles.xml
Labels: ⚡Bug, ⚙Fix
